version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: status-app-api
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: status-app
      JWT_SECRET: JWT_SECRET
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - 5001:5000
      - 9229:9229
    command: [ "node", "--inspect=0.0.0.0:9229", "index.js" ]
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: status-app-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: status-app
      MYSQL_PASSWORD: password
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: status-app
    ports:
      - 3301:3301
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
